"""add revoked_at to user role assignments

Revision ID: 3bbedc9da4af
Revises: 9a663902a6ff
Create Date: 2026-04-27 13:35:44.310238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bbedc9da4af'
down_revision: Union[str, None] = '9a663902a6ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
