"""add document table

Revision ID: 71d5494a6b9a
Revises: c7c8cb31b6a7
Create Date: 2026-05-02 16:18:43.210304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71d5494a6b9a'
down_revision: Union[str, None] = 'c7c8cb31b6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('sub_lesson_id', sa.UUID(), nullable=False),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.Column('original_name', sa.String(length=500), nullable=False),
    sa.Column('stored_name', sa.String(length=500), nullable=False),
    sa.Column('file_extension', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['sub_lesson_id'], ['sub_lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    op.create_index(op.f('ix_documents_sub_lesson_id'), 'documents', ['sub_lesson_id'], unique=False)
    op.create_index(op.f('ix_documents_uploader_id'), 'documents', ['uploader_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_uploader_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_sub_lesson_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
