"""add questions

Revision ID: f630dd057c66
Revises: a1e3f9c50d82
Create Date: 2026-05-15 11:12:34.576517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f630dd057c66'
down_revision: Union[str, None] = 'a1e3f9c50d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('sub_lesson_id', sa.UUID(), nullable=True),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('stem', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['sub_lesson_id'], ['sub_lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_questions_status', 'questions', ['status'], unique=False)
    op.create_index('idx_questions_sub_lesson', 'questions', ['sub_lesson_id'], unique=False)
    op.create_index('idx_questions_type', 'questions', ['question_type'], unique=False)
    op.create_table('question_blanks',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('blank_index', sa.SmallInteger(), nullable=False),
    sa.Column('accepted_answers', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('case_sensitive', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_blanks_question', 'question_blanks', ['question_id'], unique=False)
    op.create_table('question_choices',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('correct_order', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=20), nullable=True),
    sa.Column('match_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['question_choices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_choices_question', 'question_choices', ['question_id'], unique=False)
    op.drop_index('ix_scorm_packages_sub_lesson_current', table_name='scorm_packages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_scorm_packages_sub_lesson_current', 'scorm_packages', ['sub_lesson_id', 'is_current'], unique=False)
    op.drop_index('idx_choices_question', table_name='question_choices')
    op.drop_table('question_choices')
    op.drop_index('idx_blanks_question', table_name='question_blanks')
    op.drop_table('question_blanks')
    op.drop_index('idx_questions_type', table_name='questions')
    op.drop_index('idx_questions_sub_lesson', table_name='questions')
    op.drop_index('idx_questions_status', table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
